### ISSUE TITLE
アドバイザリーサービスを導入しましょう。

### ISSUE THREAD

**Issue by japan-ict-dao** [japan-ict-dao/JIPs#1]
Japan ICT DAOで、衰退傾向にある日本の産業（経済力）を強くすることを目的に、日本企業のICTに関わる課題・ウィークポイントに、高度IT人材が組織の枠を超え、空き時間を利用しアドバイザーとして課題解決＆担当者育成を行うサービスを導入しましょう、

**Comment by japan-ict-dao** [comment]
改善提案を準備しました。チェックをお願いいたします。
https://github.com/japan-ict-dao/JIPs/blob/main/JIPS/jip-0001.md

**Comment by abenben** [comment]
コミュニティ名が全部大文字でした。
"Japan ICT DAO"⇒"JAPAN ICT DAO"

**Comment by abenben** [comment]
修正リクエストしました
https://github.com/japan-ict-dao/JIPs/pull/2

**Comment by japan-ict-dao** [comment]
マージしました

**Comment by japan-ict-dao** [comment]
本日のキックオフで報告して、みなさんに投票してもらうことにします。
